import "@/styles/root/root.scss";
import type { Metadata } from "next";
// import styles from "./page.module.css";
import Header from "@/app/_components/Header/Header";
import Footer from "@/app/_components/Footer/Footer";
import "@/fonts/UTM/stylesheet.css";
import "@/fonts/Exo2/stylesheet.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="main beer active-glb-pale-ale">
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
